name: demandas-desenvolvimento-fuzabalta

services:
  db:
    image: postgres:16-alpine
    container_name: demandas_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: organizador_demandas
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./migrations/001_initial.sql:/docker-entrypoint-initdb.d/001_initial.sql
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: demandas_app
    restart: unless-stopped
    ports:
      - "3010:3010"
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/organizador_demandas
      JWT_SECRET: org_demandas_secret_key_2024
      PORT: "3010"
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      db:
        condition: service_healthy

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: demandas_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiOGQ2YTZmYWY4YzMwM2EzNDU2YzNlZDUwMGYzNjBlNDciLCJ0IjoiMDcxYjE2ZTgtZmQ3ZS00N2JhLWE2NTgtYTkyNTY5M2MxNmIyIiwicyI6Ik1EVXhaVEJtTkRjdE9UZzBOQzAwTTJFNUxXSm1Nekl0Wm1aak9XTTRaR0psTjJSaSJ9
    depends_on:
      - app

volumes:
  pg_data:
  uploads_data:
